### ISSUE TITLE
Broken Link: Solana on AWS documentation

### ISSUE THREAD

**Issue by chrisdotn** [aws-samples/aws-blockchain-node-runners#132]
## Description
The first link on the Solana README, pointing to solana.com is broken. This pertains to the documentation, not the code. 

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions
This is a bug in the documentation. 

The first link in the Solana README.md (lib/solana/README.md) points to a page on the solana.com, which doesn't exist. 

## Expected behavior

Link to an existing page

## Actual behavior

HTTP 404

## Additional context

I didn't find the actual page on solana.com, so I can't provide the fix.

**Comment by frbrkoala** [comment]
Thanks for reporting! Fixed. The target document no longer exists.

**Comment by frbrkoala** [comment]
Done.
