### ISSUE TITLE
Solana Single Node Base RPC Dashboard cannot display disk_used_percentage properly

### ISSUE THREAD

**Issue by lubao** [aws-samples/aws-blockchain-node-runners#138]
## Description

The disk_used_percentage widget on the Solana CloudWatch Dashboard is not displaying properly. This is because the device ID and path are mismatched. The device ID is inconsistent across deployments and may change with each new deployment

- [ X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 

- AWS CDK version:
2.154.0 (build 0fc07f3)

## Reproduction Code [Required]

Follow the document to install solana single baserpc node.

## Expected behavior

Show nvme1n1 and nvme2n1 used percentage properly.

## Actual behavior

Not working.

## Dashboard screenshot
![Screenshot 2024-11-06 at 3 03 25 PM](https://github.com/user-attachments/assets/30f99f59-1c81-416d-967e-74c7b498b28c)

## df information for 1st deployment

![Screenshot 2024-11-06 at 3 24 45 PM](https://github.com/user-attachments/assets/e5e75d03-e20e-473c-9b48-42b8900c2e2b)

## df information for 2nd deployment
![Screenshot 2024-11-06 at 9 52 32 PM](https://github.com/user-attachments/assets/8ca81cae-4456-42de-896a-b2b9125b9790)

**The combination of device ID and path changed, causing the dashboard to be unable to retrieve data**

**Comment by lubao** [comment]
The issue can be fixed by modifying the widget configuration in the control panel. Adding a section to the README to guide users on manual fixes could be a reasonable way to resolve it. Any thoughts?

**Comment by frbrkoala** [comment]
Switched the paths in dashboard config and also the sequence in the array of EBS volumes added to the single-node construct. While also not a guarantee, it worked in the last 4 deployments.
