### ISSUE TITLE
Fail to deploy consensus mainnet-beta node

### ISSUE THREAD

**Issue by lubao** [aws-samples/aws-blockchain-node-runners#142]
## Description

Encounter following error while running 
`npx cdk deploy solana-single-node --json --outputs-file single-node-deploy.json`  to deploy **Solana consensus node**:
```
/workspaces/web3-workshop/aws-blockchain-node-runners/lib/solana/lib/ha-nodes-stack.ts:79
            throw new Error("Consensus node configuration is not yet supported for HA setup");
```
- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:
- Solana

- AWS CDK version: 
- 2.154.0 (build 0fc07f3)

## Reproduction Code [Required]

```
npx cdk deploy solana-single-node --json --outputs-file single-node-deploy.json
```

1/ `cp sample-configs/.env-sample-consensus .env` 
2/ `npx cdk deploy solana-single-node --json --outputs-file single-node-deploy.json`

## Actual behavior
```
/workspaces/web3-workshop/aws-blockchain-node-runners/lib/solana/lib/ha-nodes-stack.ts:79
            throw new Error("Consensus node configuration is not yet supported for HA setup");
```
### Terminal Output Screenshot(s)

![Screenshot 2024-11-07 at 11 06 21 AM](https://github.com/user-attachments/assets/d2a827b7-8b60-46ba-8afc-3bfdb3b8d270)

**Comment by frbrkoala** [comment]
Fixed in https://github.com/aws-samples/aws-blockchain-node-runners/pull/145
