### ISSUE TITLE
Stacks Nodes on AWS

### ISSUE THREAD

**Issue by AshtonStephens** [aws-samples/aws-blockchain-node-runners#42]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

- [Stacks Ecosystem Website](https://www.stacks.co/explore/ecosystem)

A user should be able to launch a stacks node from the CDK in this repo. This repo should support at least two different binary types:
1. Stacks Signer
2. Stacks Miner

#### Describe the solution you would like

Typical CDK template specification of a stacks node.

#### Describe alternatives you have considered

N/A, this is a good supported place to host this.

#### Additional context

After corresponding with the AWS team we've decided to introduce both a Stacks miner and a Stacks signer in AWS via this repository. I'll be adding the first iteration of this feature.

**Comment by AshtonStephens** [comment]
Related pull request: https://github.com/aws-samples/aws-blockchain-node-runners/pull/49

**Comment by AshtonStephens** [comment]
Ironically, the two node types listed in this ticket are not going to be supported in the first addition of Stacks to this repository; only the follower will be added.

**Comment by frbrkoala** [comment]
Added in https://github.com/aws-samples/aws-blockchain-node-runners/pull/51
