### ISSUE TITLE
Updates required for node v18 support

### ISSUE THREAD

**Issue by ebaizel** [aws-samples/aws-blockchain-node-runners#48]
The current instructions use `node v16` to deploy the CDK templates. However v16 will be eol'ed this year (2024) so we should update to v18.

However, this will also mean updating the Cloud9 setup to use `Amazon Linux 2023`.

When I try deploying with `node v18`  I got this error:

```
node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by node)
node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by node)
```

From this thread, it seems that for >v16 support, you need to use latest Amazon Linux https://stackoverflow.com/a/72038045/657180.

To do's:
- update Cloud9 to Amazon Linux 2023
- update steps to use node v18

**Comment by frbrkoala** [comment]
Fixed in https://github.com/aws-samples/aws-blockchain-node-runners/commit/a55b215d24d5a85a06bb3976b044c93313daf168
