### ISSUE TITLE
Cloud9 Environment - Platform

### ISSUE THREAD

**Issue by varnarmat** [aws-samples/aws-blockchain-node-runners#71]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration.

If your request is for a new feature, please use the `Feature request` template.

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

Under **Create a Cloud9 environment** in the **SetupCloud9** section, it says that you should pick Amazon Linux 2 for the platform you install on your EC2 instance. However, when if you choose Amazon Linux 2 and are using Node.js version 18, you will run into issues when you run this command: 

`npm install -g aws-cdk`

The error you will likely see is this:

```
node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by node)
node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by node)
```

In order to have it working with no issues you will either have to downgrade to Node.js version 16. If you would like to use Node.js version 18, you will have to choose Amazon Linux 2023 for the platform you run on your EC2 instance. Furthermore, on the AWS console, it does say that the recommended platform is Amazon Linux 2023.

## Versions

- Module version [Required]:

- AWS CDK version:

2.138.0

### Terminal Output Screenshot(s)

With Amazon Linux 2:
![9EA2A63C-41D1-47C5-87CA-DAD744740B36](https://github.com/aws-samples/aws-blockchain-node-runners/assets/117872786/d9333ccf-1510-4b7a-80c1-0a5592d76d3a)

With Amazon Linux 2023:
![F1180708-39AE-4720-A9F5-E4BF5B5C0B0D](https://github.com/aws-samples/aws-blockchain-node-runners/assets/117872786/503c6796-d8d5-4aad-a671-71701f37912f)

The recommended platform on the console:
![18826398-D47C-45C5-A6F4-68D061F6A919_4_5005_c](https://github.com/aws-samples/aws-blockchain-node-runners/assets/117872786/9817024a-3957-487e-ae56-1c49ca4760df)

**Comment by frbrkoala** [comment]
Thank you very much for the update! I'll make a change to the Create a Cloud9 environment  doc!

**Comment by frbrkoala** [comment]
Done
