### ISSUE TITLE
hello，请问600TB天价流量费怎么解决？

### ISSUE THREAD

**Issue by AIGC2024** [aws-samples/aws-blockchain-node-runners#82]
hello，请问600TB天价流量费怎么解决？

**Comment by frbrkoala** [comment]
Hi. the best way is to talk to your account manager to see what can be done. All blockchain nodes generate a lot of traffic and there are not a lot of technical solutions to the problem:

1. Make sure you run only the number of nodes you actually need,
2. Try restricting outgoing traffic where possible (you can do it with Security Groups),
3. If you node allows, restrict the number of nodes it should maintain connection with.
