### ISSUE TITLE
What's the best practice to expose Solana RPC calls to the internet with selected ips? 

### ISSUE THREAD

**Issue by day-xy** [aws-samples/aws-blockchain-node-runners#95]
- [ Y] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

I want to call the RPC methods from my local workspace to test something. I'd like to know what the best practice is to do so. E.g., API gateway? Also, do I need to change any configuration in the script before exposing the RPC calls to the internet?

**Comment by evertonfraga** [comment]
Hi @day-xy. 

For testing, the easiest would be to include your IP on the security group that rules over your EC2 instance. 

You can choose "My IP" option on Inbound rules. And naturally, if your local IP changes, you'll have to make the change in the security group as well.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/working-with-security-groups.html#adding-security-group-rule

**Comment by frbrkoala** [comment]
There is another way using AWS Client VPN, as described in this post for Arbitrum nodes on ECS: https://aws.amazon.com/blogs/database/run-a-serverless-arbitrum-full-node-on-aws/

**Comment by frbrkoala** [comment]
UPD: created new Issue with request to add new doc: https://github.com/aws-samples/aws-blockchain-node-runners/issues/104
